### ISSUE TITLE
smoothly scrolling

### ISSUE THREAD

**Issue by nicekon** [peterpaulis/M6ParallaxController#2]
I have often used.
 Thank you.

 However, there is one problem.
 I will not be able to scroll smoothly.

  Resolved only this, but it seems to be really good

**Comment by peterpaulis** [comment]
what you mean by really smoothly?

**Comment by vicc** [comment]
When you scroll up and quickly scroll back down the scrolling is dodgy. It doesn't bounce back and instead just stops suddenly.

**Comment by forsan** [comment]
amazing... but please solve this problem... 
iphone and ipad
see this video 
http://www.youtube.com/watch?v=Aepp5kFScqs&feature=youtu.be

**Comment by peterpaulis** [comment]
Hello

Its fixed and now scrolling absolut smooth, however the table view sections support was dropped :/

**Comment by forsan** [comment]
amazing bro.. its work correctly... but i have another problem in rotate in ipad... the first time when you try to rotate the image not take the frame correctly after try to scroll first time.. the rotate work correctly
