### ISSUE TITLE
Scroll View and NavigavionController Support

### ISSUE THREAD

**Issue by metinsay** [peterpaulis/M6ParallaxController#3]
There is an error when you add parrallaxviewcontroller into a navigationcontroller. It gives a black space. And the scrollview does scrolls fluent, it stop constantly. I would appreciate if you can fix these problems.
Thank you...

**Comment by peterpaulis** [comment]
try the new code

**Comment by peterpaulis** [comment]
<pre>
- (void)viewDidAppear:(BOOL)animated {
    
    static dispatch_once_t dictPrec;
    dispatch_once(&dictPrec, ^{
        // setup
        {
            UIViewController * topViewController = [TopDesireViewController new];
            UITableViewController * tableViewController = [DesiresListingViewController new];
            
            [self setupWithTopViewController:topViewController height:230.f tableViewController:tableViewController];
            
        }
    });
    
}</pre>
