### ISSUE TITLE
parallax with nested tableview

### ISSUE THREAD

**Issue by forsan** [peterpaulis/M6ParallaxController#5]
First i would to thank you for amazing work... but i have problem, and i put it in stackoverflow... but can you help me please?

http://stackoverflow.com/questions/17019243/parallax-with-nested-tableview

**Comment by peterpaulis** [comment]
I'am not sure how it will work out, but you can try to insert the second
table view into a cell of the parent table view (probably assign the height
of the cell corresponding to the height of the inner table)

On Mon, Jun 10, 2013 at 11:49 AM, forsan notifications@github.com wrote:

> First i would to thank you for amazing work... but i have problem, and i
> put it in stackoverflow... but can you help me please?
> 
> http://stackoverflow.com/questions/17019243/parallax-with-nested-tableview
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/xelvenone/M6ParallaxController/issues/5
> .

## 

Prajem príjemný deň...
Mgr. Peter Paulis

**Comment by forsan** [comment]
im tried to but tables in parent table cell... and i think it will work but still need testing...

but any new about sections problem? God help you to solve this strange problem :+1:

**Comment by peterpaulis** [comment]
the table view sections will probably stay unsupported :(
